# Problem 1 

In [6]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array=np.array([1,-5,109,79,10])
print(array)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
kucuktenBuyuge=np.sort(array)
print(kucuktenBuyuge)



[  1  -5 109  79  10]
[ -5   1  10  79 109]


# Problem 2

In [71]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np

arr=np.array([10,15,30,45,60])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
arr=np.arange(5,15,1)


# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
arr=np.arange(50,101,5)


# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array=np.zeros(10)


# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array=np.ones(10)



# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
arr=np.arange(0,100,20)


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
arr=np.random.randint(10,31,size=5)


# 8- [-1 ile 1] arasında 10 adet sayı üretin.
arr=np.random.randint(-1,1,size=10)



# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
arr=np.random.randint(10,51,size=15)
print(arr)
yeniDizi=arr.reshape((3,5))
print(yeniDizi)


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satirToplami=yeniDizi.sum(axis=1)
sutunToplami=yeniDizi.sum(axis=0)
print(satirToplami)
print(sutunToplami)
print()
satirSayisi=yeniDizi.shape[0]
sutunSayisi = yeniDizi.shape[1]
print(f"Satir ve sutun sayi toplami:{satirSayisi+sutunSayisi}")

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(f"Uretilen matrisin en buyuk elemani : {arr.max()}")
print(f"Uretilen matrisin en kucuk elemani : {arr.min()}")
print(f"Uretilen matrisin ortalamasi : {arr.mean()}")
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(arr)
maksimumEleman=arr.max()
maksimumElemaninIndexi=np.argmax(maksimumEleman)
print(maksimumElemaninIndexi)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
sayilar=np.arange(10,21,1)
print(sayilar)
ilkUcEleman=sayilar[:3]
print(ilkUcEleman)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
tersDizi=ilkUcEleman[::-1]
print(tersDizi)

# 15- Üretilen matrisin ilk satırını seçiniz.
ilkSatir=tersDizi[:]
print(ilkSatir)


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
yeniDizi=np.arange(1,10)
yeniBoyutlandirilmisDizi=yeniDizi.reshape((3,3))
print(yeniBoyutlandirilmisDizi)
arananEleman=yeniBoyutlandirilmisDizi[1,2]
print(f"Uretilen matrisin 2.satir 3.sutunundaki eleman = {arananEleman} ")


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(f"Dizinin eleman sayisi = {yeniBoyutlandirilmisDizi.size}")
print("Dizi:")
print(yeniBoyutlandirilmisDizi)
ilkElemanlar=yeniBoyutlandirilmisDizi[:,0]
print(ilkElemanlar)

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(yeniBoyutlandirilmisDizi)
herElemaninKaresi=yeniBoyutlandirilmisDizi**2
print(herElemaninKaresi)


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
yeniDizi=np.arange(-50,51,1)
print(yeniDizi)
pozitifCiftSayilar=yeniDizi[(yeniDizi>0) & (yeniDizi%2==0)]
print(pozitifCiftSayilar)


[16 12 34 23 44 37 45 40 40 46 46 19 22 18 11]
[[16 12 34 23 44]
 [37 45 40 40 46]
 [46 19 22 18 11]]
[129 208 116]
[ 99  76  96  81 101]

Satir ve sutun sayi toplami:8
Uretilen matrisin en buyuk elemani : 46
Uretilen matrisin en kucuk elemani : 11
Uretilen matrisin ortalamasi : 30.2
[16 12 34 23 44 37 45 40 40 46 46 19 22 18 11]
0
[10 11 12 13 14 15 16 17 18 19 20]
[10 11 12]
[12 11 10]
[12 11 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Uretilen matrisin 2.satir 3.sutunundaki eleman = 6 
Dizinin eleman sayisi = 9
Dizi:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[-50 -49 -48 -47 -46 -45 -44 -43 -42 -41 -40 -39 -38 -37 -36 -35 -34 -33
 -32 -31 -30 -29 -28 -27 -26 -25 -24 -23 -22 -21 -20 -19 -18 -17 -16 -15
 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3
   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21
  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
  40  41  42  43  44